# Generated by Django 4.2.11 on 2024-05-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_healthindicator_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthindicator',
            name='body_fat',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='weight',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.RemoveField(
            model_name='healthindicator',
            name='weight',
        ),
        migrations.AddField(
            model_name='healthindicator',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
