# Generated by Django 4.2.11 on 2024-05-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_healthindicator_body_fat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthindicator',
            options={'ordering': ['date_entry']},
        ),
    ]
