# Generated by Django 4.2.11 on 2024-05-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_dietnutrition_calorie_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='weight_goal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
