# Generated by Django 4.2.11 on 2024-06-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_userprofile_weight_goal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthindicator',
            name='weight_goal',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight_goal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
