# Generated by Django 4.2.11 on 2024-06-02 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_healthindicator_weight_goal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietnutrition',
            name='user',
        ),
    ]
