# Generated by Django 4.2.11 on 2024-06-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_dietnutrition_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietnutrition',
            name='id',
        ),
        migrations.AlterField(
            model_name='dietnutrition',
            name='food',
            field=models.CharField(default='Unknown Food', max_length=100, primary_key=False, serialize=False),
        ),
    ]
