# Generated by Django 4.2.11 on 2024-06-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_dietnutrition_id_alter_dietnutrition_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietnutrition',
            name='calorie_unit',
        ),
        migrations.AlterField(
            model_name='dietnutrition',
            name='date_entry',
            field=models.DateField(blank=True, primary_key=False, serialize=False),
        ),
        migrations.AlterField(
            model_name='dietnutrition',
            name='food',
            field=models.CharField(default='Unknown Food', max_length=100),
        ),
    ]
