# Generated by Django 4.2.11 on 2024-06-02 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_dietnutrition_date_entry_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DietNutrition',
        ),
    ]
