# Generated by Django 4.2.11 on 2024-06-02 10:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_dietnutrition_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietnutrition',
            name='user',
        ),
        migrations.AlterField(
            model_name='dietnutrition',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for food', primary_key=True, serialize=False),
        ),
    ]
