# Generated by Django 4.2.11 on 2024-06-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_remove_dietnutrition_user_alter_dietnutrition_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietnutrition',
            name='food',
            field=models.CharField(max_length=100),
        ),
    ]
