# Generated by Django 4.2.11 on 2024-06-02 11:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_dietnutrition_food_alter_dietnutrition_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietnutrition',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for food', primary_key=True, serialize=False),
        ),
    ]
