# Generated by Django 4.2.11 on 2024-06-03 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_alter_dietnutrition_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dietnutrition',
            name='unique_user_food_date_entry',
        ),
    ]
