# Generated by Django 4.2.11 on 2024-06-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_remove_dietnutrition_unique_user_food_date_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietnutrition',
            name='user',
            field=models.ManyToManyField(to='catalog.userprofile'),
        ),
    ]
