# Generated by Django 4.2.11 on 2024-06-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_dietnutrition_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietnutrition',
            name='macro',
        ),
        migrations.AddField(
            model_name='dietnutrition',
            name='grams_carbs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='dietnutrition',
            name='grams_fat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='dietnutrition',
            name='grams_fibre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='dietnutrition',
            name='grams_protein',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
